#chudu
#2020.12.25

#Status code


OBJ_CHECK_SUCCESS = "-400"
OBJ_CHECK_ERROR_INPUT_FILE_NOT_EXIST = "-401"
OBJ_CHECK_ERROR_UNZIP_ERROR = "-402"
OBJ_CHECK_ERROR_INPUT_NOT_ZIP_NOT_FOLDER = "-403"
OBJ_CHECK_RESOURCE_HAS_ERROR = "-404"
OBJ_CHECK_CHECK_OBJ_NOT_OK = "-405"
OBJ_CHECK_MORE_THAN_ONE_OBJ_FILE_FOUND = "-406"
OBJ_CHECK_NO_MODEL_OBJ_FOUND = "-407"
OBJ_CHECK_NO_OBJ_FILE_FOUND = "-408"
OBJ_CHECK_OBJ_FILE_NOT_OK = "-409"
OBJ_CHECK_NO_MTL_FOUND = "-410"
OBJ_CHECK_MTL_RESOURCE_NOT_MATCH = "-411"



OBJ_PACK_SUCCESS = "-500"
OBJ_PACK_INPUT_NOT_ZIP = "-501"
OBJ_PACK_CHECK_ZIP_ERROR = "-502"
OBJ_PACK_ENCOUNTER_ERROR = "-503"
OBJ_PACK_ENCOUNTER_ERROR1 = "-504"
OBJ_PACK_OUTPUT_NOT_ZIP = "-505"


OBJ_PROCESS_INFO = {
    OBJ_CHECK_SUCCESS : "OBJ_CHECK_SUCCESS",
    OBJ_CHECK_ERROR_INPUT_FILE_NOT_EXIST : "OBJ_CHECK_ERROR_INPUT_FILE_NOT_EXIST",
    OBJ_CHECK_ERROR_UNZIP_ERROR : "OBJ_CHECK_ERROR_UNZIP_ERROR",
    OBJ_CHECK_ERROR_INPUT_NOT_ZIP_NOT_FOLDER: "OBJ_CHECK_ERROR_INPUT_NOT_ZIP_NOT_FOLDER",
    OBJ_CHECK_RESOURCE_HAS_ERROR: "OBJ_CHECK_RESOURCE_HAS_ERROR",
    OBJ_CHECK_CHECK_OBJ_NOT_OK: "OBJ_CHECK_CHECK_OBJ_NOT_OK",
    OBJ_CHECK_NO_OBJ_FILE_FOUND: "OBJ_CHECK_NO_OBJ_FILE_FOUND",
    OBJ_CHECK_MORE_THAN_ONE_OBJ_FILE_FOUND: "OBJ_CHECK_MORE_THAN_ONE_OBJ_FILE_FOUND",
    OBJ_CHECK_NO_MODEL_OBJ_FOUND:"OBJ_CHECK_NO_MODEL_OBJ_FOUND",
    OBJ_CHECK_OBJ_FILE_NOT_OK:"OBJ_CHECK_OBJ_FILE_NOT_OK",
    OBJ_CHECK_NO_MTL_FOUND:"OBJ_CHECK_NO_MTL_FOUND",
    OBJ_CHECK_MTL_RESOURCE_NOT_MATCH:"OBJ_CHECK_MTL_RESOURCE_NOT_MATCH",

    OBJ_PACK_SUCCESS:"OBJ_PACK_SUCCESS",
    OBJ_PACK_INPUT_NOT_ZIP:"OBJ_PACK_INPUT_NOT_ZIP",
    OBJ_PACK_CHECK_ZIP_ERROR:"OBJ_PACK_CHECK_ZIP_ERROR",
    OBJ_PACK_ENCOUNTER_ERROR:"OBJ_PACK_ENCOUNTER_ERROR",
    OBJ_PACK_ENCOUNTER_ERROR1:"OBJ_PACK_ENCOUNTER_ERROR1",
    OBJ_PACK_OUTPUT_NOT_ZIP:"OBJ_PACK_OUTPUT_NOT_ZIP"
    
}

def setStatusCode(code, returnStatusCode):
    returnStatusCode["msgCode"] = code
    returnStatusCode["msgInfo"] = OBJ_PROCESS_INFO[code]
    returnStatusCode["success"] = False
